defaults:
    experiment:
        model_file: examples/output_debug/<EXP>.mod
        hyp_file: examples/output_debug/<EXP>.hyp
        out_file: examples/output_debug/<EXP>.out
        err_file: examples/output_debug/<EXP>.err
        run_for_epochs: 1
        eval_only: True
        eval_metrics: recall|nbest=1,recall|nbest=5,recall|nbest=10
    train:
        pretrained_model_file: /pylon5/ci560op/mingxing/xnmt/examples/speech_retriever_batch128_adam0.0002.mod
        batch_strategy: 'shuffle'
        trainer: 'adam'
        learning_rate: 0.005 
        default_layer_dim: 512
        dropout: 0.0
        dev_metrics: recall|nbest=1,recall|nbest=5,recall|nbest=10
        training_corpus: !BilingualTrainingCorpus
            train_src: examples/data/mfcc_tr20.npz
            train_trg: examples/data/flickr_tr20.ids
            dev_src: examples/data/mfcc_tx20.npz
            dev_trg: examples/data/flickr_tx20.ids
        corpus_parser: !BilingualCorpusParser
            src_reader: !ContVecReader
              transpose: True
            trg_reader: !IDReader {}
        model: !DotProductRetriever
            src_embedder: !NoopEmbedder
                emb_dim: 40
            src_encoder: !HarwathSpeechEncoder
                filter_height: [40, 1, 1]
                filter_width: [5, 25, 25]
                channels: [1, 64, 512]
                num_filters: [64, 512, 1024]
                stride: [1, 1, 1]
            trg_embedder: !NoopEmbedder
                emb_dim: 40
            trg_encoder: !HarwathImageEncoder
                in_height: 4096
                out_height: 1024 
            database: !StandardRetrievalDatabase
                reader: !ContVecReader
                  transpose: True
                database_file: examples/data/vgg20.npz
    decode:
        src_file: examples/data/mfcc_tx20.npz 
    evaluate:
        ref_file: examples/data/flickr_tx20.ids

speech_retriever_default:
