defaults:
    experiment:
        model_file: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/output/<EXP>.mod
        hyp_file: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/output/<EXP>.hyp
        out_file: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/output/<EXP>.out
        err_file: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/output/<EXP>.err
        run_for_epochs: 20
        eval_metrics: recall|nbest=1,recall|nbest=5
    train:
        trainer: 'adam'
        learning_rate: 0.01 
        default_layer_dim: 512
        dropout: 0.0
        dev_metrics: recall|nbest=1,recall|nbest=5
        training_corpus: !BilingualTrainingCorpus
            train_src: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/data/filelist_tr_40k.txt
            train_trg: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/data/flickr_tr_40k.txt  #examples/data/flickr_tr20.ids
            dev_src: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/data/filelist_val_40k.txt  #examples/data/mfcc_tx20.npz
            dev_trg: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/data/flickr_val_40k.txt  #dev_trg: examples/data/flickr_tx20.ids
        corpus_parser: !BilingualCorpusParser
            src_reader: !ContVecNPYReader {}
            trg_reader: !IDReader {}
            #max_num_train_sents: 100
        model: !DotProductRetriever
            src_embedder: !NoopEmbedder
                #vocab_size: 5000 # TODO: set this automatically
                emb_dim: 40
            src_encoder: !HarwathSpeechEncoder
                filter_height: [40, 1, 1]
                filter_width: [5, 25, 25]
                channels: [1, 64, 512]
                num_filters: [64, 512, 1024]
                stride: [1, 1, 1]
            trg_embedder: !NoopEmbedder
                emb_dim: 40
            trg_encoder: !HarwathImageEncoder
                in_height: 4096
                out_height: 1024 
            database: !StandardRetrievalDatabase
                reader: !ContVecReader {}
                database_file: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/data/vgg_40k.npz
    decode:
        src_file: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/data/filelist_tx_40k.tx  #examples/data/mfcc_tx20.npz
    evaluate:
        ref_file: /pylon2/ci560op/odette/tools/xnmt_retriever/xnmt/examples/data/flickr_tx_40k.txt #examples/data/flickr_tx20.ids

standard-dropout0.1:
    train:
       dropout: 0.1
