standard:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    cfg_file: examples/output/<EXP>.yaml
    run_for_epochs: 30
    eval_metrics: bleu
  train: !TrainingRegimen
    batcher: !SentShuffleBatcher
      batch_size: 100
    glob:
      dropout: 0.2
      default_layer_dim: 512
    restart_trainer: False
    trainer: !TransformerAdamTrainer
      alpha: 1.0
      warmup_steps: 4000
    lr_decay: 1.0
    dev_metrics: bleu
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !PlainTextReader {}
      training_corpus: !BilingualTrainingCorpus
        train_src: examples/data/train-big.ja
        train_trg: examples/data/train-big.en
        dev_src: examples/data/dev.ja
        dev_trg: examples/data/dev.en
    model: !TransformerTranslator
      src_embedder: !SimpleWordEmbedder {}
      encoder: !TransformerEncoder
        layers: 1
      trg_embedder: !SimpleWordEmbedder {}
      decoder: !TransformerDecoder
        layers: 1
        label_smoothing: 0.0
  decode:
    beam: 1
    src_file: examples/data/test.ja
  evaluate:
    ref_file: examples/data/test.en
